### ISSUE TITLE
Fazer deploy

### ISSUE THREAD

**Issue by bruno3du** [OliveiraJess/todo-react#2]
Assim como no caso do readme, o deploy é um apelo visual para o seu projeto, mas além disso vai ser interativo, ou seja, qualquer pessoa vai poder navegar e interagir com o seu projeto. Assim recrutadores que não sabem codar também podem ver o seu resultado. Como dica recomendo a netlify para fazer deploys, o plano gratuito já é bem generoso e você vai poder usar para contruir seus projetos de portfólio

**Comment by OliveiraJess** [comment]
Bom dia.
Feito!
https://vercel.com/oliveirajess/todo-react
